services:
  database:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: shrt
      POSTGRES_PASSWORD: password
      PGPORT: 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

  shrt:
    depends_on:
      database:
        condition: service_healthy
    build:
      dockerfile: $PWD/Dockerfile
    image: shrt
    environment:
      PORT: 4000
      DB_URL: postgres://shrt:password@database:5432/shrt?sslmode=disable
    ports:
      - '4000:4000'